### ISSUE TITLE
Stackoverflow link issue

### ISSUE THREAD

**Issue by ChandanChainani** [preyashyadav/preyashyadav#1]
@Preyash-tryin-to-code Currently the link looks like this `https://stackoverflow.com/users/https://stackoverflow.com/users/16488334/preyash` it should be `https://stackoverflow.com/users/16488334/preyash`

**Comment by preyashyadav** [comment]
Hiiii @ChandanChainani thank you so much for pointing out this issue, I'll fix it 😊

**Comment by preyashyadav** [comment]
Or do u wanna fix this issue?
I can assign you this.

**Comment by ChandanChainani** [comment]
Yeah sure

**Comment by preyashyadav** [comment]
I assigned you, after you fix it, just open a Pull Request. I'll merge it and thankyou 😊
